<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsbDoctor.Core\UsbDoctor.Core.csproj" />
    <ProjectReference Include="..\UsbDoctor.Fat\UsbDoctor.Fat.csproj" />
  </ItemGroup>

</Project>
