<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>smartlab</AssemblyName>
    <RootNamespace>SmartLab.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartLab.Engine\SmartLab.Engine.csproj" />
    <ProjectReference Include="..\SmartLab.Maintenance\SmartLab.Maintenance.csproj" />
  </ItemGroup>

</Project>
