<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartLab.Core\SmartLab.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="builtin-signatures.json" />
  </ItemGroup>

</Project>
