<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsbDoctor.Core\UsbDoctor.Core.csproj" />
    <ProjectReference Include="..\UsbDoctor.Signatures\UsbDoctor.Signatures.csproj" />
    <ProjectReference Include="..\UsbDoctor.Win32\UsbDoctor.Win32.csproj" />
  </ItemGroup>

</Project>
