<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>usbdoctor</AssemblyName>
    <RootNamespace>UsbDoctor.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsbDoctor.Engine\UsbDoctor.Engine.csproj" />
    <ProjectReference Include="..\UsbDoctor.Maintenance\UsbDoctor.Maintenance.csproj" />
  </ItemGroup>

</Project>
